---
name: Build

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Hello World
        run: ./bf examples/hello.b
